# Generated by Django 3.0.1 on 2022-11-11 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20220731_0132'),
        ('ratings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
            ],
        ),
        migrations.AddField(
            model_name='useritemratingline',
            name='item_rating',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lineitems', to='ratings.ItemRating'),
            preserve_default=False,
        ),
    ]
