# Generated by Django 3.0.1 on 2022-11-12 20:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0002_auto_20221111_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useritemratingline',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
