# Generated by Django 3.0.1 on 2022-11-12 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0003_auto_20221112_2011'),
        ('products', '0004_auto_20220731_0132'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rating_collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rating_collection', to='ratings.ItemRating'),
        ),
    ]
